---
- name: set hostname Pt.1
  shell: cat /etc/hostname
  register: hostname_reg
  when: not(hostname is defined) or (hostname is none)

- name: set hostname Pt.2
  set_fact:
    hostname: "{{ hostname_reg.stdout }}"
  when: not(hostname is defined) or (hostname is none)

- name: consul config file
  template: >
    src=consul.json.j2
    dest={{ consul_config_file }}
    owner={{consul_user}}
    group={{consul_group}}
    mode=0644
  notify:
    - restart consul

- name: consul config services file
  template: >
    src=consul.services.json.j2
    dest={{ consul_services_file }}
    owner={{consul_user}}
    group={{consul_group}}
    mode=0644

- name: copy consul configuration files
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }} owner={{ item.owner }} group={{ item.group }}
  with_items: "{{ consul_copy_dirs_files }}"
  when: (consul_copy_dirs_files is defined) and not(consul_copy_dirs_files is none)

